// npm run build. Everything that is generated from pets.json and the pets' sheets:
//
//   art/frames/<id>/<mood>.png   each pet's nine moods, 256px, transparent  (build-frames.mjs)
//   art/frames/index.json        what was built, and which pets are still placeholders
//   cage-data.js                 the registry and frame paths for cage.html
//   ROSTER.md                    the running list of who lives here
//   README.md                    the pet table between the pets:start / pets:end markers
//   art/roster.png               every pet in every mood on one labelled sheet
//
// This replaces build-art.mjs, which drew the original 32x32 pets by hand.
// Generating new art is separate and costs money: see generate-pets.mjs.
import { readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { buildFrames } from './build-frames.mjs';
import { buildRoster } from './roster.mjs';
import { applyTable } from './lib.mjs';
import { MOODS, decodePng } from './sheet-to-sprites.mjs';

process.chdir(fileURLToPath(new URL('..', import.meta.url)));

const metadataOnly = process.argv.includes('--metadata-only');
const { index, missing } = metadataOnly
  ? { index: JSON.parse(readFileSync('art/frames/index.json', 'utf8')), missing: [] }
  : buildFrames({ log: () => {} });
const registry = JSON.parse(readFileSync('pets.json', 'utf8'));

const idleBounds = (path) => {
  const { width, height, rgba } = decodePng(readFileSync(path));
  let left = width, top = height, right = 0, bottom = 0;
  for (let y = 0; y < height; y++) for (let x = 0; x < width; x++) if (rgba[(y * width + x) * 4 + 3] > 0) {
    left = Math.min(left, x); top = Math.min(top, y); right = Math.max(right, x + 1); bottom = Math.max(bottom, y + 1);
  }
  return right > left ? [left, top, right, bottom] : [0, 0, width, height];
};

// cage.html loads this with a plain <script src>, so the page still works when double-clicked.
// Only paths go in here; the pictures stay as image files next to it.
const data = {
  registry,
  moods: MOODS,
  size: index.size,
  frames: Object.fromEntries(Object.entries(index.pets).map(([id, p]) => [id, p.frames])),
  bounds: Object.fromEntries(Object.entries(index.pets).map(([id, p]) => [id, idleBounds(p.frames.idle)])),
  placeholders: Object.entries(index.pets).filter(([, p]) => p.placeholder).map(([id]) => id),
};
writeFileSync('cage-data.js', `// Generated by scripts/build.mjs from pets.json and art/frames/. Do not edit by hand.\nwindow.CAGE_DATA = ${JSON.stringify(data)};\n`);

const names = Object.fromEntries([
  ...(registry.pets || []).map((p) => [p.art, p.pet]),
  ...(registry.mascots || []).map((m) => [m.art, m.name]),
]);
writeFileSync('ROSTER.md', buildRoster(registry, MOODS, names, data.frames));

const readme = readFileSync('README.md', 'utf8');
const nextReadme = applyTable(readme, registry);
if (nextReadme !== readme) writeFileSync('README.md', nextReadme);

if (!metadataOnly) execFileSync(process.execPath, ['scripts/frames-sheet.mjs', '--thumb', '96'], { stdio: 'ignore' });

const placeholders = data.placeholders;
console.log(metadataOnly
  ? `Updated registry and docs for ${registry.pets.length} pets using existing ${index.size}px frames.`
  : `Built ${Object.keys(index.pets).length} pets x ${MOODS.length} moods at ${index.size}px: frames, cage-data.js, ROSTER.md, README table, art/roster.png.`);
if (placeholders.length) console.log(`Placeholder art (regenerate when you can): ${placeholders.join(', ')}`);
if (missing.length) { console.error(`No art at all for: ${missing.join(', ')}`); process.exit(1); }
