// Draws every character, then writes:
//   art/sprites.json            all frames (palette + 32 rows each)
//   art/png/<id>/<mood>.png     each frame at 8x on a transparent background
//   art/roster-sheet.png        every pet x every mood on one sheet (row order = PETS, column order = MOODS)
//   cage-data.js                pets.json + sprites for cage.html (so it also works when double-clicked)
//   ROSTER.md                   the running list of who lives here
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname } from 'node:path';
import { Cv, W, H, png, blit } from './art-kit.mjs';
import { PETS, MOODS, render, pack, allSprites } from './pets-art.mjs';
import { buildRoster } from './roster.mjs';

const p = (f) => fileURLToPath(new URL(`../${f}`, import.meta.url));
const write = (f, data) => { mkdirSync(dirname(p(f)), { recursive: true }); writeFileSync(p(f), data); };

const sprites = allSprites();
const registry = JSON.parse(readFileSync(p('pets.json'), 'utf8'));

write('art/sprites.json', JSON.stringify({ size: [W, H], moods: MOODS, sprites }, null, 1) + '\n');

// individual PNGs
const SCALE = 8;
for (const def of PETS) for (const mood of MOODS) {
  const cv = render(def, mood);
  const buf = Buffer.alloc(W * SCALE * H * SCALE * 4);
  blit(buf, W * SCALE, cv.px, SCALE, 0, 0);
  write(`art/png/${def.id}/${mood}.png`, png(W * SCALE, H * SCALE, buf));
}

// contact sheet
const S = 4, GAP = 6, cell = W * S + GAP;
const sw = cell * MOODS.length + GAP, sh = cell * PETS.length + GAP;
const sheet = Buffer.alloc(sw * sh * 4);
for (let i = 0; i < sw * sh; i++) { sheet[i * 4] = 0x1d; sheet[i * 4 + 1] = 0x18; sheet[i * 4 + 2] = 0x24; sheet[i * 4 + 3] = 255; }
PETS.forEach((def, r) => MOODS.forEach((mood, c) => {
  // a lighter tile behind each frame so dark outlines read
  for (let y = 0; y < H * S; y++) for (let x = 0; x < W * S; x++) { const i = ((GAP + r * cell + y) * sw + GAP + c * cell + x) * 4; sheet[i] = 0x34; sheet[i + 1] = 0x2c; sheet[i + 2] = 0x3e; }
  blit(sheet, sw, render(def, mood).px, S, GAP + c * cell, GAP + r * cell);
}));
write('art/roster-sheet.png', png(sw, sh, sheet));

// data for the page and the roster
write('cage-data.js', `// Generated by scripts/build-art.mjs from pets.json and art/sprites.json. Do not edit by hand.\nwindow.CAGE_DATA = ${JSON.stringify({ registry, size: [W, H], moods: MOODS, sprites })};\n`);
write('ROSTER.md', buildRoster(registry, MOODS, Object.fromEntries(Object.entries(sprites).map(([id, s]) => [id, s.name]))));
console.log(`Drew ${PETS.length} characters x ${MOODS.length} moods = ${PETS.length * MOODS.length} frames.`);
